.gitignore, LICENSE, README.md, bootstrap/config/manager/manager.yaml, controlplane/config/manager/manager.yaml
A small number of changes after testing with tilt. Running with tilt requires [this bug](https://github.com/kubernetes-sigs/cluster-api/pull/7482) and until that merges you will need to apply the changes locally to your capi clone.
Added some initial instructions in the README about how to get started. These will be migrated to a contributing guide in time. 
Fixes #9 
**Checklist**:
=> Tilt changes

bootstrap/api/v1alpha1/rke2config_types.go, bootstrap/api/v1alpha1/rke2configtemplate_types.go, bootstrap/api/v1alpha1/webhook_suite_test.go, bootstrap/main.go, controlplane/main.go, go.mod
=> Improve main.go after scaffolding 

Makefile
Fixes an issue with the make target name for docker push
Fixes #
**Checklist**:
=> fix: spelling mistake for target

.github/workflows/release.yml, Makefile, bootstrap/internal/controllers/rke2config_controller.go, pkg/rke2/registries_test.go, pkg/util/util.go
This PR implements a GitHub Action for releasing new versions of the provider. It also fixes a small issue which potentially causes a nil pointer dereference in the Bootstrap controller.
**Checklist**:
=> Github action for releasing new versions

Makefile, samples/aws/external/cluster-template-external-cloud-provider.yaml
Small fix to the AWS manifests to make the cloud controller deploy correctly
This PR fixes an issue with release manifest generation and AWS sample deployment manifests.
Fixes #
**Checklist**:
=> Fix typo in Makefile for Bootstrap provider

samples/vmware/README.md, samples/vmware/cluster.yaml, samples/vmware/machinedeployment.yaml, samples/vmware/namespace.yaml, samples/vmware/rke2configtemplate.yaml, samples/vmware/rke2controlplane.yaml, samples/vmware/vmware-cpi-with-csi.yaml, samples/vmware/vspherecluster.yaml, samples/vmware/vspheremachinetemplate.yaml
Updated VMware example files due to updates to the RKE2 Provider
This config uses the external VMware Cloud Provider (kublet arg `cloud-provider=external`), due to this the taint `node.cloudprovider.kubernetes.io/uninitialized` is set. Because of this taint the coredns pods wont start, so no DNS. Therfor the cloud provider cannot reach the vCenter server and set the providerId on the node. Without providerId the node isn't marked ready. By adding a toleration to the coredns pods this is solved. The toleration is set in the RKE2ControlPlane spec with a HelmChartConfig file.
More information: [https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/) …
=> Updated VMware example files due to updates to the RKE2 Provider

bootstrap/api/v1alpha1/rke2config_types.go, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml, bootstrap/internal/cloudinit/cloudinit.go, bootstrap/internal/cloudinit/cloudinit_test.go, bootstrap/internal/cloudinit/controlplane_init.go, bootstrap/internal/cloudinit/worker_join.go, bootstrap/internal/controllers/rke2config_controller.go, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml, pkg/consts/global_consts.go, pkg/rke2/config.go, pkg/rke2/config_test.go, pkg/util/util.go, pkg/util/util_test.go, samples/docker/cis-profile/rke2-sample.yaml
This PR better implements the CIS Profile by differenciation RKE2 version that are <v1.25 which need a profile `cis-1.5` or `cis-1.6` and the versions >=v1.25, which need a profile `cis-1.23` replacing Pod Security Policies with Pod Security Admission.
It also fixes an issue where the node was not correctly prepared before RKE2 service starts, causing a failure during RKE2's installation.
Fixes #28
**Checklist**:
=> Fixed #28 CIS Profile now works and is different for v1.25+ and v1.24-

bootstrap/api/v1alpha1/rke2config_types.go, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
The comment on the ExtraArgs field in ComponentConfig struct in the Bootstrap API suggests that the field should be a map whereas the field is actually a slice of strings with the format `flag=value`. This PR fixes this comment which appears as a field description when using `kubectl explain`.
Fixes #112
**Checklist**:
=> Fixed a mistake in the description of ExtraArgs field

bootstrap/internal/controllers/rke2config_controller.go, pkg/consts/global_consts.go, pkg/rke2/config.go, pkg/rke2/config_test.go, pkg/secret/certificates.go
This PR moves some constants and hard-coded values into public constants, in order to have a single reference for their values.
Fixes #81
**Checklist**:
=> moved useful constants to own package

.github/workflows/e2e.yml, Makefile
Change to use the kustomize from the tools folder instead of the version built into the image (i.e. via tyhe PATH).
Also added a schedule to the e2e workflow.
Fixes #
**Checklist**:
=> chore: change to use explicit kustomize path

image-builder/Makefile, image-builder/README.md, image-builder/aws/opensuse-1504.json, image-builder/aws/packer.json, image-builder/aws/ubuntu-2204.json, image-builder/scripts/opensuse/bootstrap.sh, image-builder/scripts/ubuntu/bootstrap.sh
Let's start RKE2 image builder, it will be using packer similar to CAPI one https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi. There will be a config for each supported cloud platform and linux distro. This PR adds AWS images for openSUSE and ubuntu.
We can automate building images with github actions later.
Fixes #
**Checklist**:
=> RKE2 Image builder

controlplane/api/v1alpha1/rke2controlplane_types.go, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml, controlplane/config/manager/manager.yaml, controlplane/internal/controllers/rke2controlplane_controller.go, samples/aws/external/cluster-template-external-cloud-provider.yaml, samples/docker/disable-components/rke2-sample.yaml
This PR fixes an issue with Kubebuilder validation of the field `disablePlugin` field of the `RKE2ControlPlane` resource.
Fixes #128
This is a simple change in the location of kubebuilder annotation for the enum validation.
**Checklist**:
=> Fix for disablePlugin field not validated correctly

.golangci.yml, bootstrap/internal/controllers/rke2config_controller.go, bootstrap/internal/ignition/clc/clc.go, bootstrap/internal/ignition/clc/clc_test.go, bootstrap/internal/ignition/ignition.go, bootstrap/internal/ignition/ignition_test.go, go.mod, samples/aws/README.md, samples/aws/ignition-external/cluster-template-aws-ignition-external-cloud-provider.yaml
Add support for ignition based user data. It similar to what is implemented for kubeadm, I also added a cluster template and instructions for bootstrapping.
Fixes https://github.com/rancher-sandbox/cluster-api-provider-rke2/issues/66
**Checklist**:
=> Support ignition format for generating user data

Makefile, bootstrap/api/v1alpha1/rke2config_webhook.go, controlplane/api/v1alpha1/rke2controlplane_types.go, controlplane/api/v1alpha1/rke2controlplane_webhook.go, controlplane/api/v1alpha1/types.go, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml, controlplane/internal/controllers/rke2controlplane_controller.go, docs/registration-methods.md, pkg/registration/registration.go, pkg/registration/registration_test.go, pkg/rke2/control_plane.go, test/e2e/helpers.go
This adds support for different ways to register new nodes into the cluster.
Fixes #136
Fixes #146 
**Checklist**:
=> feat: support different registration methods

controlplane/api/v1alpha1/rke2controlplane_webhook.go, pkg/registration/registration_test.go, samples/docker/kube-vip/rke2-sample.yaml
With the recent change to introduce new registration methods we started to default the `advertiseAddress` to the "registration address" if the registration method of `address` was used. This caused the kube-api server to be startedw tith that address. If you then used a VIP/LB solution like kube-vip or metalb that runs within cluster it caused pods to not start start as there is a chicken and egg scenario.
This change removes that defaulting and also adds a sample that uses kube-vip.
Fixes #
**Checklist**:
=> fix: incorrectly defaulting advertise address

bootstrap/internal/ignition/butane/butane.go, bootstrap/internal/ignition/butane/butane_test.go
Currently, bootstrap script used in igntion config runs each time the machine is booted, if machine is rebooted for some reason we try to install RKE2 again.
This PR adds a check to the systemd unit that looks for `/run/cluster-api/bootstrap-success.complete` and runs script only if path doesn't exist.
Fixes #
**Checklist**:
=> Run ignition bootstrap script only once

pkg/rke2/config.go
This reverts a previous change so that a user can choose whether to disable ttheeh cloud controller or not
Fixes #197 
**Checklist**:
=> Re-enable ability to choose to disable cloud controller

bootstrap/internal/ignition/butane/butane.go, bootstrap/internal/ignition/ignition.go, bootstrap/internal/ignition/ignition_test.go
=> Create bootstrap-success before setting selinux to enforcing mode

bootstrap/internal/controllers/rke2config_controller.go
The RKE2 Config controller is creating the registration token twice (intermittently) and updating the secret that contains the token so different nodes are trying to get registered with different tokens and failing to do so.
We must ensure [this secret](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/c69285302e9d3733559f65a2ef8031935e0144e4/bootstrap/internal/controllers/rke2config_controller.go#L337) is created once and its value remains unedited so that nodes can be registered to the cluster.
This initial proposal suggests detecting if the secret exists and skip token creation if it does.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR …
=> fix: rke2 registration token generated twice

bootstrap/internal/controllers/rke2config_controller.go
This backports changes in the original PR #236 to `release-0.2`.
Fixes #
**Checklist**:
=> :bug: Fix rke2 registration token being created twice - backport to `release-0.2`

pkg/rke2/config.go
Extra arguments passed to `etcd` are defined in `rke2AgentConfig` which is embedded in `rke2ServerConfig`. The issue occurs when we generate control plane configuration and populate these two structures, here:
```go
func GenerateInitControlPlaneConfig(opts ServerConfigOpts) (*rke2ServerConfig, []bootstrapv1.File, error) {
if opts.Token == "" {
return nil, nil, fmt.Errorf("token is required")
}
rke2ServerConfig, serverFiles, err := newRKE2ServerConfig(opts)
if err != nil {
return nil, nil, fmt.Errorf("failed to generate rke2 server config: %w", err)
}
rke2AgentConfig, agentFiles, err := newRKE2AgentConfig(AgentConfigOpts{
AgentConfig: opts.AgentConfig,
Client:      opts.Client,
Ctx:         opts.Ctx,
Token:       opts.Token,
})
if err != nil {
return …
```
=> fix: etcd extra args not passed to etcd

pkg/rke2/config.go, pkg/rke2/config_test.go
If S3 storage is specified and used, set the etcdSnapshotDir to S3 folder and use local directory when local storage is utilized
Fixes #
**Checklist**:
=> Make etcd snapshot location configurable

Makefile, metadata.yaml, test/e2e/config/e2e_conf.yaml, test/e2e/data/infrastructure/cluster-template-docker.yaml, test/e2e/e2e_test.go
=> fix: failing e2e tests

controlplane/internal/controllers/rke2controlplane_controller_test.go, pkg/rke2/control_plane.go, pkg/rke2/workload_cluster.go, pkg/rke2/workload_cluster_test.go
It seems that in some child clusters provisioned node names are different from machine names, causing control plane to loose node reference. This fix ensures that all machine collections refer to an actual nodeName reference if one is found upon provisioning.
Fixes #257
Fixes #224
**Checklist**:
=> :bug: Ensure we always lookup machines by node name from collection

pkg/rke2/config.go, pkg/rke2/config_test.go
If S3 storage is specified and used, set the etcdSnapshotDir to S3 folder while use local directory when local storage is utilized
Signed-off-by: Furkat Gofurov <furkat.gofurov@suse.com>
(cherry picked from commit 261395ea390109e7fa4637f4f15261675dfbc08e)
Fixes #
**Checklist**:
=> [release-0.2] Differentiate etcd backup location based on the parameters

controlplane/api/v1beta1/rke2controlplane_types.go, controlplane/api/v1beta1/types.go, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml, controlplane/internal/controllers/rke2controlplane_controller.go, pkg/registration/registration.go, pkg/registration/registration_test.go
This adds a new registration method that will use the **host** from the control plane endpoint set on the **Cluster**. This is aimed at users that will use an external LB in front of the control-plane machines.
Fixes #
**Checklist**:
=> feat: added control plane endpoint registration method

bootstrap/internal/ignition/butane/butane.go
The rke2-install.sh script sets the exit on error flag ('set -e'), however the script might fail to exit when a command in a pipe fails. Add the '-u' and '-o pipefail' flags to better identify errors within the install script.
Fixes #276
=> Let the rke2-install.sh fail for pipe errors and undefined variables

bootstrap/api/v1beta1/rke2config_types.go, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml, bootstrap/internal/controllers/rke2config_controller.go, controlplane/api/v1beta1/rke2controlplane_types.go, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml, controlplane/internal/controllers/rke2controlplane_controller.go, controlplane/internal/controllers/scale.go, pkg/rke2/config.go, pkg/rke2/config_test.go, pkg/rke2/control_plane.go, pkg/rke2/machine_filters.go, pkg/rke2/machine_filters_test.go, pkg/util/util.go, pkg/util/util_test.go, test/e2e/data/infrastructure/cluster-template-docker.yaml, test/e2e/helpers.go
Use spec.Version field as primarily source of RKE2 version. Currently, it's just a placeholder for satisfying API contracts. When both spec.AgentConfig.Version and spec.Version are specified, spec.Version take precedence.
Fixes #
**Checklist**:
=> Use spec.Version field as primarily source

controlplane/internal/controllers/rke2controlplane_controller.go, pkg/rke2/workload_cluster.go, pkg/rke2/workload_cluster_test.go
kind/bug
This should fix the behavior around setting the `controlPlane.Status.Initialized` flag. 
As per [documentation](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane#required-status-fields), this flag is:
```text
a boolean field that is true when the target cluster has completed initialization such that at least once, the target's control plane has been contactable.
```
The implementation is in line with Kubeadm, but instead of checking if the `kubeadm-config` ConfigMap was uploaded on the cluster, we check if the `rke2-serving` secret was.
This should be equivalent and as well a good enough marker that the control plane was indeed initialized.
This should fix the RKE2 control …
=> Check rke2-serving secret to determine controlPlane.Status.Initialized

pkg/registration/registration_test.go
Gomega's `HaveExactElements` causes intermittent test failures because order is not guaranteed. Since order is not relevant in these scenarios, we could use the alternative `ContainElements`, which checks the content of the slice but not the order of its elements, plus length validation.
Fixes #241 
**Checklist**:
=> test: use gomega's ContainElements

bootstrap/internal/controllers/rke2config_controller.go, controlplane/internal/controllers/rke2controlplane_controller.go
Fixes #82 
Fixes #
**Checklist**:
=> Review and update incorrectly returned results

bootstrap/internal/controllers/rke2config_controller.go, pkg/rke2/machine_filters.go, pkg/rke2/machine_filters_test.go
We need to ensure that any change of `RKE2ConfigTemplate` is causing CP machines re-rollout.
Fixes #307 
**Checklist**:
=> :bug: Check MachineConfig spec for full equality with Rke2CPSpec

samples/aws/README.md, samples/aws/external/cluster-template-external-cloud-provider.yaml, samples/aws/ignition-external/cluster-template-aws-ignition-external-cloud-provider.yaml, samples/aws/internal/cluster-template.yaml
Fixes https://github.com/rancher-sandbox/cluster-api-provider-rke2/issues/329
**Checklist**:
=> Update AWS out-of-tree examples

metadata.yaml, test/e2e/config/e2e_conf.yaml, test/e2e/e2e_suite_test.go, test/e2e/e2e_upgrade_test.go
Adds metadata for release-0.4
Fixes #
**Checklist**:
=> Add release-0.4 metadata

pkg/rke2/registries.go, pkg/rke2/registries_types.go
The registry TLS configuration requires the 3 values ca.crt, tls.crt, tls.key when only ca.crt is required (in case the registry does not need the client certs). With the current code, you're not able to include only the ca.crt. Also, there's no way to include the insecureSkipVerify flag to remove the rest of certs (we're skipping)
Fixes #
**Checklist**:
=> Fix issue with registries required fields

Makefile, bootstrap/config/default/manager_image_patch.yaml, controlplane/config/default/manager_image_patch.yaml, test/e2e/config/e2e_conf.yaml, tilt-provider.json
=> [release-0.4] Change organisation name in Makefile

test/e2e/e2e_suite_test.go, test/e2e/e2e_upgrade_test.go
Revert back legacy e2e tests to its original state as it was introduced in https://github.com/rancher/cluster-api-provider-rke2/commit/a7b3b2fc7e7e8a6d68a12f3804b529e8289a2547 and work on refactoring (splitting out legacy and normal e2e tests in a follow-up PR) change once this is merged and e2e is back to green [hopefully].
Fixes #
**Checklist**:
=> Revert back legacy e2e tests to its original state

test/e2e/e2e_suite_test.go, test/e2e/e2e_upgrade_test.go
Signed-off-by: Furkat Gofurov <furkat.gofurov@suse.com>
(cherry picked from commit 7ed376e41e979698cee7d3201654491c4fcad36b)
Fixes: #391 
**Checklist**:
=> [release-0.5] Revert back legacy e2e tests to its original state

bootstrap/config/manager/manager.yaml, controlplane/config/manager/manager.yaml
kind/bug
**What this PR does / why we need it**: Without `securityContext` set for the manager containers, RKE2 bootstrap and control-plane providers cannot be installed into an RKE2 cluster with cis-profile set (e.g. creating a hardened RKE2 cluster and pivoting the management cluster into it).
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: 
Fixes #384
**Checklist**:
=> add securityContext to the manager containers

README.md
Fix providers.yaml in README from https://github.com/rancher/cluster-api-provider-rke2/pull/277
Fixes #
**Checklist**:
=> docs: fix providers.yaml example in readme

bootstrap/internal/cloudinit/controlplane_init.go, bootstrap/internal/ignition/ignition.go
ensures that cluster-etcd secret can be created if host does not have kubectl installed
fixes #403
kind/bug
**Checklist**:
=> fix: use absolute path to rke2's kubectl binary

Makefile
`time` is not present on the GCP-hosted runner and prevents us from running test suite there.
Fixes #
**Checklist**:
=> Remove time command from e2e

bootstrap/internal/ignition/butane/butane.go
This aligns with the [default cloud-init behavior](https://cloudinit.readthedocs.io/en/latest/reference/modules.html#write-files) and enables e.g overwriting distro-default files via RKE2ConfigTemplate using the spec.template.spec.files API.
With this we can see the example mentioned in #410 now works as expected the empty `/etc/motd` is overwritten.
```
worker-0 login: root
Password: 
hello 123
```
kind/bug
Fixes #410
=> Overwrite files with format: ignition

bootstrap/internal/ignition/butane/butane.go, bootstrap/internal/ignition/ignition.go, bootstrap/internal/ignition/ignition_test.go, pkg/consts/global_consts.go, pkg/rke2/config.go
Currently there are some stray tabs which break the rendered output, replace these with spaces and add some unit test coverage.
kind/bug
Currently the cisProfile option is broken when selecting ignition format for Leap/SLEMicro deployments
Fixes: #401
**Checklist**:
=> Fix cisProfile option with ignition format

samples/docker/clusterclass/clusterclass-quick-start.yaml, samples/docker/clusterclass/rke2-sample.yaml
The original ClusterClass examples that was added when the feature was included in the provider was no longer valid. This updates class and cluster definition to make it work with the current version of the provider.
This can be used as reference to cover ClusterClass provisioning in existing E2E tests.
Fixes #
**Checklist**:
=> chore: fix clusterclass example

docs/release.md
Add a post-release actions section to release guide.
Fixes #
**Checklist**:
=> :book: docs: add pre-release actions to release guide

test/e2e/common.go, test/e2e/e2e_clusterclass_test.go, test/e2e/e2e_suite_test.go, test/e2e/e2e_test.go, test/e2e/e2e_upgrade_test.go, test/e2e/helpers.go
This PR fixes e2e test failures, related to:
- Metrics and pod logs collection.
- MachineDeployment checks for running machines. MachineSets are picked at random, as they are indistinguishable based on labels, and belong to the same MachineDeployment. This causes flakes as old MachineSet is expected to scale accordingly, while the new one performed it instead.
- Increased ClusterClass apply timeouts. CAPD webhooks may take longer to stand up.
- Improved failure reason reporting for `WaitForClusterToUpgrade`
Fixes #439 
**Checklist**:
=> 🐛 E2E failures in CI

controlplane/api/v1beta1/rke2controlplane_types.go, controlplane/internal/controllers/rke2controlplane_controller.go, controlplane/internal/controllers/scale.go, pkg/rke2/control_plane.go, test/e2e/data/infrastructure/clusterclass-template-docker.yaml
=> Implement etcd member management in pre-terminate hook

bootstrap/internal/ignition/butane/butane.go, bootstrap/internal/ignition/butane/butane_test.go
Leap/SLEMicro don't include ntpd so the current approach doesn't work
kind/bug
Currently the `ntp.servers` API provided e.g by `RKE2ControlPlane` does not work for Leap/SLEMicro, because chrony is used not ntpd as currently configured.
Fixes #430
**Checklist**:
=> bootstrap: switch to chrony for ignition config

docs/book/src/01_user/01_getting-started.md
Change GitHub links from relative to absolute.
**Checklist**:
=> fix: Make GH links absolute

pkg/rke2/config.go
In order to be able to use a field from rke2ServerConfig struct in https://github.com/rancher/turtles/issues/719, make it public 
Fixes #
**Checklist**:
=> 🌱 Rename rke2ServerConfig to make it public

controlplane/api/v1beta1/rke2controlplane_types.go, controlplane/internal/controllers/rke2controlplane_controller.go
RKE2 uses kubelet local mode, so this this check should not be conditional based on version.
Fixes #
**Checklist**:
=> 🌱 Ensure draining hook is removed last

metadata.yaml, test/e2e/config/e2e_conf.yaml, test/e2e/e2e_suite_test.go, test/e2e/e2e_upgrade_test.go
Follows the post new minor release tasks described in https://github.com/rancher/cluster-api-provider-rke2/blob/main/docs/release.md#tasks
Fixes #
**Checklist**:
=> 🌱 Prepare main branch for v0.8 development

docs/book/src/01_user/01_getting-started.md, samples/docker/online-default/rke2-sample.yaml
Makes sure the getting started guide for creating CAPRKE2+CAPD works as expected when following the guide
Fixes #
**Checklist**:
=> 🐛 Update getting started notes

bootstrap/internal/cloudinit/controlplane_init.go, bootstrap/internal/ignition/ignition.go, bootstrap/internal/ignition/ignition_test.go, pkg/rke2/management_cluster.go, pkg/rke2/workload_cluster.go, pkg/secret/certificates.go
This change ensures that in all cases, etcd certificate is fetched from local (management) cluster, to perform etcd membership management, unless the certificate is not available, which skips this operation.
Fixes #449 
**Checklist**:
=> Always use CAPI generated certificates for etcd management

docs/release.md
Update release docs to include reference on post-release activities, and requirements to mark release as non-draft.
Other potential changes which are **not** included:
- Notify users in according channels
Fixes #
**Checklist**:
=> 📖 Update notes on post-release activities

bootstrap/internal/controllers/rke2config_controller.go, controlplane/api/v1beta1/rke2controlplane_types.go, controlplane/internal/controllers/rke2controlplane_controller.go, controlplane/internal/controllers/scale.go, pkg/secret/certificates.go
This change allows to disable ETCD certificate management and provisioning with CAPI generated certificates for legacy control planes via `controlplane.cluster.x-k8s.io/legacy` annotation.
This annotation is meant to be set on RKE2 CP, upgraded from 0.2.z to version 0.3+. When the child cluster does not have `cluster-etcd` secret created, and the `<cluster-name>-etcd` secret in the management cluster does not contain the external `cluster.x-k8s.io/purpose` label, then this cluster requires the annotation to be set.
This would ensure that automatically generated ETCD certificates by CAPI will not be used for new ETCD replicas in provisioned nodes, replacing existing set and creating 2 separate etcd groups.
This change is a followup to #449 
**Which …
=> Allow to distinguish legacy CP without ETCD management via annotation

pkg/rke2/machine_filters.go
This agent installation command is not executed during bootstrap process, due to `sudo` prefix. Changing it to a correct command, causes machines to re-rollout after successful bootstrap endlessly.
Part of https://github.com/rancher/turtles/issues/763
**Checklist**:
=> 🐛 Prevent machine re-rollout on system agent start command

controlplane/internal/controllers/rke2controlplane_controller.go
Fixes an issue during deletion of RKE2 CP annotated with `controlplane.cluster.x-k8s.io/legacy`, allowing pre-terminate node drain hook to be removed as usual.
Requires a cherry-pick on release-0.7
Fixes #
**Checklist**:
=> Fix: remove pre-terminate drain hook for legacy CP

.github/workflows/release.yml
Path for secret read from vault seems to be incorrect compared to https://github.com/rancher-eio/read-vault-secrets?tab=readme-ov-file#example-workflow. 
Another example: https://github.com/rancher/backup-restore-operator/blob/5cc7bccaeaa6fcb44a8bc8ede18a53dfbe1ad9f6/.github/workflows/publish.yaml#L58
Fixes #
**Checklist**:
=> Fix repo path for reading a secret from vault

.github/workflows/release.yml
Reverts: #463, #464, #465 and https://github.com/rancher/cluster-api-provider-rke2/pull/459/commits/c902e98efc7f6a64bb05e52f021b04a76bbff932 from #459 to unblock release GH temporarily. 
Prime image building needs to be added back once we sort out secret creation in vault by EIO.
Fixes #
**Checklist**:
=> [release-0.7] Revert prime image building changes

.github/workflows/release.yml
Reverts: https://github.com/rancher/cluster-api-provider-rke2/pull/462 and https://github.com/rancher/cluster-api-provider-rke2/pull/456 to unblock release GH temporarily.
Prime image building needs to be added back once we sort out secret creation in vault by EIO.
Fixes #
**Checklist**:
=> Revert prime image building changes 

controlplane/api/v1alpha1/rke2controlplane_types.go, controlplane/internal/controllers/rke2controlplane_controller.go
It is not always possible to apply annotation in some environments, so this patch and release can automate it.
Fixes #
Ensure that legacy CP contain annotation after upgrade to `v0.2.8`.
cc @alexander-demicev 
**Checklist**:
=> Patch legacy annotation on pre 0.3 RKE2 control planes

.github/workflows/release.yml
Second try to enable Prime image building previously reverted due to issue with secret reading from EIO vault.
Based off https://github.com/rancher/cluster-api-provider-rke2/commit/c902e98efc7f6a64bb05e52f021b04a76bbff932 and slight changes on top of original one
Fixes #
As usual, this patch is not possible to test on CI nor on fork 😞 but I am hoping for it to work
Related to: https://github.com/rancherlabs/eio/issues/2696
**Checklist**:
=> Build and Push Prime images using prime registry secrets from vault

docs/book/src/02_topics/03_cis-psa.md, docs/book/src/SUMMARY.md
Add docs that describe how to configure a custom PSA when CIS profile is enabled.
Fixes #
**Checklist**:
=> Add a CIS and PSA configuration docs

pkg/rke2/config.go
kind/feature
All CIDRs should be passed to RKE2 server config. 
This fix is related to #337
**Checklist**:
=> Pass multiple CIDRs to RKE2 server config

.devcontainer/devcontainer.json, .github/workflows/ci.yml, .github/workflows/e2e-test.yml, .github/workflows/e2e.yml, .github/workflows/golangci-lint.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .golangci.yml, Dockerfile, Makefile, examples/docker/air-gapped/image-building/files/install.sh, go.mod, hack/tools/go.mod
Support only amd64/armd64 archs and publish images to speed up the image building process. We might consider adding other archs in the future based on the need and demand from the users.
To further speed up build process, this patch removes redundant steps from Dockerfile. The mod-related steps are redundant because go build handles downloading dependencies as needed already and the existing build step is already configured to cache them, so there shouldn't be any meaningful difference in build times when dependencies are added/updated.
Last, we bump go version to v1.22.x to keep it more or less newer.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …
=> feat: Improvements to make image buildings faster

docs/book/src/01_user/01_getting-started.md, docs/book/src/02_topics/01_air-gapped-installation.md
A couple of file links are not working due to a previous restructure of the docs.
Fixes #489
**Checklist**:
=> docs: Fix file references

.github/workflows/pr-md-link-check.yml, .markdown-link-check.json, README.md, docs/book/src/03_examples/01_aws.md, docs/old/RKE2 Cluster API Provider - Data Type definitions.md
This PR adds a CI workflow that checks for broken links in MD files. The workflow is currently configured to run on each PR as well as manually (mostly to be able to test it once merged).
Upstream CAPI workflows use a 3rd party [action](https://github.com/gaurav-nelson/github-action-markdown-link-check) to achieve the same, which we could use but it will require approval by RST to be able to run it in this repo. And since this action [is no longer supported](https://github.com/gaurav-nelson/github-action-markdown-link-check?tab=readme-ov-file#--update-may-2024-), I thought it would be best to invoke the [tool](https://github.com/tcort/markdown-link-check) that the 3rd party action is using under the hood.
Fixes #493 …
=> ci: Check for broken links in MD files

pkg/etcd/etcd.go
gRPC's `WithBlock` is deprecated and using it will prevent us from updating `google.golang.org/grpc`.
Fixes #488 
We can create a specific context and pass it to `clientv3.Config` so it manages timeouts and cancellations. This will prevent operations from hanging indefinitely.
**Checklist**:
=> fix: remove deprecated grpc.WithBlock

Makefile, controlplane/internal/controllers/rke2controlplane_controller_test.go
Bumping envtest to v1.32 and setting a timeout in one test case prevents flakes we see in CI
Fixes https://github.com/rancher/cluster-api-provider-rke2/issues/417
**Checklist**:
=> Bump envtest to 1.32

Makefile, bootstrap/config/certmanager/certificate.yaml, bootstrap/config/certmanager/kustomizeconfig.yaml, bootstrap/config/crd/kustomization.yaml, bootstrap/config/crd/kustomizeconfig.yaml, bootstrap/config/crd/patches/cainjection_in_rke2configs.yaml, bootstrap/config/crd/patches/cainjection_in_rke2configtemplates.yaml, bootstrap/config/crd/patches/webhook_in_rke2configs.yaml, bootstrap/config/default/kustomization.yaml, bootstrap/config/default/kustomizeconfig.yaml, bootstrap/config/default/manager_webhook_patch.yaml, bootstrap/config/default/webhookcainjection_patch.yaml, bootstrap/config/webhook/kustomizeconfig.yaml, controlplane/config/certmanager/certificate.yaml, controlplane/config/certmanager/kustomizeconfig.yaml, controlplane/config/crd/kustomization.yaml, controlplane/config/crd/kustomizeconfig.yaml, controlplane/config/crd/patches/cainjection_in_rke2controlplanes.yaml, controlplane/config/crd/patches/cainjection_in_rke2controlplanetemplates.yaml, controlplane/config/default/kustomization.yaml, controlplane/config/default/kustomizeconfig.yaml, controlplane/config/default/manager_webhook_patch.yaml, controlplane/config/default/webhookcainjection_patch.yaml, controlplane/config/webhook/kustomizeconfig.yaml
Bumps kustomize to v5 and removes deprecated syntax of Kustomize:
- patchesStrategicMerge -> patches
- vars and varReference -> replacements
- bases -> resources
Fixes #406 
**Checklist**:
=> Bump kustomize to v5

controlplane/internal/controllers/rke2controlplane_controller.go
Recreates the kubeconfig after half of the expiration period (1 year, renews 6 months). See similar code in kubeadm control plane [here](https://github.com/kubernetes-sigs/cluster-api/blob/92e16dbdaead4dd3e1f9ebec2c0d395733d63d5f/controlplane/kubeadm/internal/controllers/helpers.go#L98)
**Which issue(s) this PR fixes**
**Checklist**:
=> Rotate kubeconfig before it expires

.golangci.yml, bootstrap/internal/controllers/rke2config_controller.go, pkg/rke2/config.go, pkg/rke2/config_test.go
Fixes https://github.com/rancher/cluster-api-provider-rke2/issues/524
**Checklist**:
=> Add indentation to generated RKE2 config

pkg/rke2/config.go, pkg/rke2/config_test.go
Fixes #499 
~Reverts: https://github.com/rancher/cluster-api-provider-rke2/commit/261395ea390109e7fa4637f4f15261675dfbc08e~
**Checklist**:
=> 🐛 Fix setting folder S3 on etcd backups

docs/book/src/01_user/01_getting-started.md
Previous [PR](https://github.com/rancher/cluster-api-provider-rke2/pull/559) did not update all instances of env var.  Note that the user guide does not _currently_ work with [this](https://github.com/rancher/cluster-api-provider-rke2/blob/main/examples/docker/online-default/cluster-template.yaml) template, most likely because we need to release a new version of the provider.
**Checklist**:
=> docs: Use correct env var

Dockerfile
After adding cross-compilation for image building to other projects, we have experienced an optimized, faster build process and we can use the same principle to create the provider's multi-architecture images.
Fixes #
**Checklist**:
=> feat: add dockerfile cross-compilation for multi-platform images

pkg/rke2/config.go, pkg/rke2/config_test.go
kind/bug
This fixes the absence of the `cloud-provider-name` in the generated `/etc/rancher/rke2/config.yaml`
Consider this an hotfix. Due to the nature of the code, it seems to generate duplicate files. It's safe to ignore. 
A proper fix would probably need refactoring of the entire bootstrap generation logic to make it more maintainable and understandable.
For example: 
```json
{
Path: "/etc/rancher/rke2/audit-policy.yaml",
Owner: "root:root",
Permissions: "0644",
Encoding: "",
Content: "test_audit",
ContentFrom: nil,
},
{
Path: "/etc/rancher/rke2/cloud-provider-config",
Owner: "root:root",
Permissions: "0644",
Encoding: "",
Content: "test_cloud_config",
ContentFrom: nil,
},
{
Path: "/etc/rancher/rke2/etcd-s3-ca.crt",
Owner: "root:root", …
```
=> Propagate cloud provider config

docs/book/src/04_developer/01_development.md
Lays out the steps to attach debugger to a CAPRKE2 process running in developer setup. We need it for easier troubleshooting/debugging on part of the developers.
Fixes # NA
**Checklist**:
=> Provides steps to attach debugger to CAPRKE2

pkg/rke2/control_plane.go
`UpToDateMachines` method operates on `c.Machines` and removes the result of `c.MachinesNeedingRollout()` from it. This result doesn't include machines being deleted because `MachinesNeedingRollout` method removes them in the beginning of the definition using:
```go
// Ignore machines to be deleted.
machines := c.Machines.Filter(collections.Not(collections.HasDeletionTimestamp))
```
Thus duplication of code to ensure machines being deleted aren't calculated in updatedReplicas
Fixes #355 
The way I kept a tab on the `updatedReplicas` count was using below commands (in separate terminals, of course):
```sh
$ watch -c -n1 "kubectl get rke2controlplane rke2-docker-control-plane -o …
```
=> 🐛 Filter machines being deleted from updatedReplicas count

bootstrap/api/v1beta1/rke2config_webhook.go, bootstrap/api/v1beta1/rke2config_webhook_test.go, bootstrap/api/v1beta1/rke2configtemplate_webhook.go, bootstrap/api/v1beta1/webhook_suite_test.go, bootstrap/main.go, controlplane/api/v1beta1/rke2controlplane_webhook.go, controlplane/api/v1beta1/rke2controlplanetemplate_webhook.go, controlplane/api/v1beta1/rke2controlplanetemplate_webhook_test.go, controlplane/api/v1beta1/webhook_suite_test.go, controlplane/main.go
kind/*
**What this PR does / why we need it**: `admission.Validator` and `admission.Defaulter` were [marked as Deprecated in controller-runtime v0.17.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.17.0). They are [removed in controller-runtime v0.20.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.20.0). This addresses the removal and bumps the controller-runtime dependency to [0.20.1](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.20.1) (latest stable)
Fixes #
**Checklist**:
=> 🌱 Bump controller-runtime to 0.20.1 and related changes

examples/aws/cluster-template.yaml, pkg/rke2/workload_cluster_test.go
=> Fix cloud provider installation in AWS template

bootstrap/config/manager/manager.yaml, bootstrap/internal/controllers/rke2config_controller.go, bootstrap/internal/controllers/rke2config_scope.go, bootstrap/internal/controllers/rke2config_scope_test.go, bootstrap/main.go, pkg/rke2/workload_cluster_test.go
kind/feature
This PR adds support for MachinePool, plus some refactoring.
Fixes #569
**Checklist**:
=> MachinePool support

controlplane/api/v1beta1/rke2controlplane_types.go, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
Existing comment seems to be copy paste and creates confusion for users. This PR adds better documentation for the field and its meaning in the context of RKE2 CP resource.
Fixes #356 
**Checklist**:
=> Clarify RKE2 CP Ready field meaning in status

.github/workflows/ci.yml, .github/workflows/e2e.yml, .github/workflows/golangci-lint.yml, .github/workflows/lint.yml
This change enables [merge-queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) on PRs, which should make all PRs merge sequentially with rebases on top of each other.
After merging this PR, we can lift the requirement for PRs to be always up-to-date with main.
Fixes #
**Checklist**:
=> Use merge queue to reduce rebase effort

controlplane/internal/controllers/scale.go, test/e2e/data/infrastructure/cluster-template-docker-updated.yaml, test/e2e/data/infrastructure/cluster-template-docker.yaml, test/e2e/e2e_upgrade_test.go, test/e2e/helpers.go
$subject. For details, refer #517.
Fixes #517 
1. This PR has two commits. First one modifies the function signature and requires a change at all places it's called. Second one uses a `for` loop to make changes only at the place where I think it's reuired. Please suggest which commit to keep of the two.
2. I have tested this using the following manifest:
<details>
<summary> manifest </summary>
```yaml
apiVersion: v1
kind: Namespace
metadata:
name: example-docker
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
name: rke2-docker
namespace: …
```
=> Adds RKE2ControlPlane labels to Machines

test/e2e/e2e_upgrade_test.go, test/e2e/helpers.go
This PR verifies unwanted rollouts do not happen on the provider upgrade.
The e2e test has been extended to ensure the Machines are the same after an upgrade.
Part of #596 
Fixes #
**Checklist**:
=> Add e2e test to prevent Machine rollout on provider upgrade

bootstrap/internal/controllers/rke2config_controller.go, bootstrap/main.go, controlplane/internal/controllers/rke2controlplane_controller.go, controlplane/main.go
This PR enables concurrency on the Control Plane and Bootstrap controllers.  Currently both accept a "--concurrency" flag but the flag does not do anything.  Enabling concurrency can improve controller responsiveness when scaling up the number of managed clusters.
Fixes #614
**Checklist**:
=> Enable concurrency in controllers

bootstrap/api/v1beta1/rke2config_webhook.go
When configuring RKE2ControlPlane with a file using `gzip+base64` encoding, the bootstrap controller fails with the error : 
```
spec.files[2].encoding: Forbidden: not supported when spec.format is set to "ignition"
```
Even if the format used is cloud-init.
This PR validates the file encoding is not `gzip` or `gzip+base64` __only__ in case of ignition format.
=> Allow using Gzip and GzipBase64 encoding in case of cloud-init format

bootstrap/internal/ignition/ignition.go, bootstrap/internal/ignition/ignition_test.go
Flatcar OS doesn't have `semanage` due to missing python from base distro. This PR removes semanage command from rke2-install only if `additionalIgnition` have `variant: flatcar` set
Fixes #
**Checklist**:
=> Render rke2-install without semanage for flatcar

controlplane/internal/controllers/rke2controlplane_controller.go, controlplane/internal/controllers/rke2controlplane_controller_test.go, controlplane/internal/controllers/suite_test.go, pkg/kubeconfig/kubeconfig.go, pkg/rke2/management_cluster.go, pkg/rke2/workload_cluster_test.go, test/helpers/envtest.go
This is a continuation of #550 
The existing functionality added by #521 did not look correct, as it was trying to create an existing secret, therefore I assume it would fail.
I fixed it to patch the Secret instead.
Fixes #520 
**Checklist**:
=> Add kubeconfig rotate tests

bootstrap/internal/ignition/butane/butane.go, bootstrap/internal/ignition/butane/butane_test.go, bootstrap/internal/ignition/ignition_test.go
By writing into /etc/ssh/sshd_config we override default config which usually defines include /etc/ssh/sshd_config.d/*.conf. This breaks an ability to cusomize config further. And disables include any files dropped into sshd_config.d directory.
This commit moves RKE2 sshd config into subdirectory with 010 index so it will be loaded first.
kind/bug
Fixes #
**Checklist**:
=> Move sshd config into included subdir

bootstrap/config/manager/manager.yaml, controlplane/config/manager/manager.yaml, controlplane/internal/controllers/rke2controlplane_controller.go, pkg/rke2/control_plane.go, pkg/rke2/machine_filters.go, pkg/rke2/machine_filters_test.go, test/e2e/config/e2e_conf.yaml
This PR prevents unwanted machine rollouts when the `.spec.infrastructureRef` is in use, before it has been defaulted to `.spec.machineTemplate.infrastructureRef`. 
Also adds debug log trail to identify machine rollout reasons.
Note that verbosity level is on 5, since this can get very spammy on a Cluster with many control plane nodes.
One example would look like: 
```
I0514 07:04:14.155345       1 machine_filters.go:203] "Machine RKE2 version 'v1.30.4+rke2r1' does not match desired version 'v1.31.0+rke2r1'. Needs rollout." controller="rke2controlplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="RKE2ControlPlane" RKE2ControlPlane="create-workload-cluster-v45egw/caprke2-e2e-5vb932-control-plane" …
```
=> Prevent Machine rollouts before machineTemplate has been updated

bootstrap/config/manager/manager.yaml, controlplane/config/manager/manager.yaml, controlplane/internal/controllers/rke2controlplane_controller.go, pkg/rke2/control_plane.go, pkg/rke2/machine_filters.go, pkg/rke2/machine_filters_test.go, test/e2e/config/e2e_conf.yaml
Backport of https://github.com/rancher/cluster-api-provider-rke2/pull/651
Fixes #
**Checklist**:
=> [0.15] Prevent Machine rollouts before machineTemplate has been updated

bootstrap/internal/ignition/ignition.go, bootstrap/internal/ignition/ignition_test.go
systemctl enable + systemctl start can be combined into one. also move it after the restorecon. This potentially allows dropping the setenforce disablement
Fixes #
**Checklist**:
=> Simplify service start

bootstrap/config/manager/manager.yaml, controlplane/config/manager/manager.yaml, docs/book/src/02_topics/05_configure-manager-options.md, docs/book/src/SUMMARY.md
kind/feature
kind/documentation
Allows configuring following feature-gate & manager flags:
- ClusterTopology : featureGate
- namespace : flag
- concurrency  : flag
Fixes #588 
**Checklist**:
=> Configures usage of feature-gate & manager flags

bootstrap/api/v1beta1/rke2config_webhook.go, bootstrap/api/v1beta1/rke2config_webhook_test.go, bootstrap/api/v1beta1/rke2configtemplate_webhook.go, bootstrap/internal/cloudinit/cloudinit.go, bootstrap/internal/cloudinit/cloudinit_test.go
kind/bug
This is a followup PR to fix things we missed out in #719.
Fixes #
**Checklist**:
=> Follow-up AdditionalUserData.Data formatting difference 

pkg/rke2/config.go, pkg/rke2/config_test.go
kind/bug
Add the missing `SystemDefaultRegistry` to `AgentConfig`.
Fixes #723
<details><summary>I used the following <code>RKE2ControlPlane</code> to test.</summary>
<p>
```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlane
metadata:
name: pvala-rke2-system-default-registry-control-plane
namespace: pvala-ns
spec: 
replicas: 1
version: v1.31.7+rke2r1
registrationMethod: control-plane-endpoint
rolloutStrategy:
type: "RollingUpdate"
rollingUpdate:
maxSurge: 1
agentConfig:
systemDefaultRegistry: docker.io
gzipUserData: false …
```
=> Add SystemDefaultRegistry to AgentConfig

bootstrap/internal/controllers/rke2config_controller.go, bootstrap/internal/controllers/rke2config_scope.go
This fixes a panic when `version` is not set. Also returns a contextualized error message.
Fixes #750 
**Checklist**:
=> [fix] Return error on missing k8s version
