- .github/workflows/ci.yml
- bootstrap/internal/controllers/suite_test.go
- controlplane/internal/controllers/suite_test.go
Fix CRD paths in envtest setup and enable tests in CI
Fixes https://github.com/rancher-sandbox/cluster-api-provider-rke2/issues/10
**Checklist**:
> Fix CRD paths in envtest setup

- README.md
> Fix repo link in readme

- bootstrap/api/v1alpha1/condition_consts.go
- controlplane/api/v1alpha1/condition_consts.go
- controlplane/internal/controllers/const.go
- controlplane/internal/controllers/scale.go
- pkg/machinefilters/machine_filters.go
- pkg/rke2/config.go
- pkg/rke2/control_plane.go
- pkg/rke2/failure_domain.go
- pkg/rke2/machine_collection.go
- pkg/rke2/management_cluster.go
- pkg/rke2/workload_cluster.go
- pkg/util/util.go
- version/version.go
Fix license year and add where its missing
Fixes #
**Checklist**:
> Fix license year and add where its missing

- samples/vmware/README.md
- samples/vmware/cluster.yaml
- samples/vmware/machinedeployment.yaml
- samples/vmware/namespace.yaml
- samples/vmware/rke2configtemplate.yaml
- samples/vmware/rke2controlplane.yaml
- samples/vmware/vmware-cpi-with-csi.yaml
- samples/vmware/vspherecluster.yaml
- samples/vmware/vspheremachinetemplate.yaml
kind/examples
Add example manifiest for provisioning RKE2 clusters on VMware.
Missing examples for VMware
**Checklist**:
> Example manifests for VMWare

- .github/workflows/golangci-lint.yml
- .golangci.yml
- Makefile
Signed-off-by: Aniruddha Basak <codewithaniruddha@gmail.com>
kind/feature
This PR contains the golangci-lint config & necessary GitHub actions so whenever a new PR open we have a clear picture of where the lint is falling and we also follow best practices while writing code for future readability of the project.
Fixes #11 
It's just an initial phase I added and I need some reviews from the community where I can improve the PR.
**Checklist**:
> Add .golangci.yml config & golangci-lint.yml github action

- README.md
This PR comes with the first release. It updates the documentation by providing a **Getting Started** section in the README.
Fixes #
**Checklist**:
> Adding a Getting Started section to the README

- samples/metal3/sample-cluster.yaml
Assumptions:
1. Two networks, provisioning and public network. Provision network is internal and use for bare metal provisioning. Public network can access all the public endpoints.
2. Public network is VLAN.
Fixes #
**Checklist**:
> Add metal3 example

- Makefile
- bootstrap/api/v1alpha1/rke2config_types.go
- bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
- bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
- bootstrap/internal/cloudinit/cloudinit.go
- bootstrap/internal/cloudinit/cloudinit_test.go
- bootstrap/internal/cloudinit/controlplane_init.go
- bootstrap/internal/cloudinit/controlplane_join.go
- bootstrap/internal/cloudinit/worker_join.go
- bootstrap/internal/controllers/rke2config_controller.go
- controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
- go.mod
> implemented additionCloudInit configuration in the API

- .github/workflows/e2e.yml
Changed the GHA event type for the e2e tests
Fixes #
**Checklist**:
> chore: change event trigger

- pkg/locking/control_plane_init_mutex_test.go
Slightly increase the test coverage in the locking package, uncovered through coverage analysis.
**Checklist**:
> controlplane/locking: increase test coverage

- README.md
Updates the README.md to the newest provider version. Avoids confusion by not using older-versions in example
Fixes # Confusion in #156
**Checklist**:
- [ X] includes documentation
> Updating  ~/.cluster-api/clusterctl.yaml versions in README

- controlplane/internal/controllers/rke2controlplane_controller_test.go
- controlplane/internal/controllers/suite_test.go
- pkg/rke2/workload_cluster.go
kind/bug
Fixes #
**Checklist**:
> Fix nil machine occurence during upgrade

- metadata.yaml
Bump the metadata version for the release
Fixes #
**Checklist**:
> chore: update metadata for v0.2 release

- .github/workflows/e2e.yml
The e2e tests are running out of space. This adds an action to cleanup some space.
Fixes #
**Checklist**:
> test: add disk space cleanup

- bootstrap/internal/ignition/ignition.go
- bootstrap/internal/ignition/ignition_test.go
Fixes https://github.com/rancher-sandbox/cluster-api-provider-rke2/issues/198
**Checklist**:
> Fix selinux in ignition for SLE micro

- bootstrap/internal/ignition/ignition.go
- bootstrap/internal/ignition/ignition_test.go
This is a cherry-pick of https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/205
Fixes # 
**Checklist**:
> [release-0.2] Fix selinux in ignition for SLE micro

- bootstrap/internal/ignition/butane/butane.go
- bootstrap/internal/ignition/ignition.go
- bootstrap/internal/ignition/ignition_test.go
Cherry pick of https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/209
Fixes #
**Checklist**:
> [release-0.2] Create bootstrap-success before setting selinux to enforcing mode

- bootstrap/api/v1beta1/rke2config_types.go
- bootstrap/api/v1beta1/rke2config_webhook.go
- bootstrap/api/v1beta1/rke2config_webhook_test.go
- bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
- bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
- controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
- pkg/rke2/registries.go
> fix: Handling of registries config to work as rke2

- bootstrap/api/v1alpha1/rke2config_webhook.go
- pkg/rke2/registries.go
This is amanual cherry-pick of #251 (fix by @ekarlso ).
Relates #253
**Checklist**:
> [cherry-pick] feat: Fix handling of registries config to work as rke2

- .github/workflows/e2e-test.yml
Adding a copy of the e2es configured to run in self hosted runners. This is for testing only
Fixes #
**Checklist**:
> chore: added additional workflow to test self hosted e2e

- bootstrap/internal/controllers/rke2config_controller.go
We allow specifying file location in a secret though API but handling secrets is missing from controller code. 
Fixes #
**Checklist**:
> Fetch additional files from secrets

- bootstrap/internal/controllers/rke2config_controller.go
Cherry-picking https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/273
Fixes #
**Checklist**:
> [release-0.2] Fetch additional files from secrets

- .devcontainer/devcontainer.json
- .github/dependabot.yml
This adds a devcontainer to the project. It assumes that you have also clone cluster api in the relative location. This enables a reproducible enviroment. 
Fixes #
**Checklist**:
> feat: add devcontainer

- samples/aws/internal/cluster-template.yaml
For CAPA, we need to explicitly add an ingress rule to the CP load balancer to get traffic from outside. This field is intended to override all default values, meaning that users must supply all ingress rules or rely on default.
Fixes #
**Checklist**:
> Fix ingress rules in AWS example

- docs/adr/0000-template.md
- docs/adr/0001-separate-CP-and-worker-versions.md
Fixes #323 
Fixes #
**Checklist**:
> 📖 Add ADR for using separate CP and worker versions

- controlplane/api/v1beta1/rke2controlplane_types.go
- controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
- controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
Fixes https://github.com/rancher/turtles/issues/580
**Checklist**:
> 🐛 Fix regex to support more then one patch version number

- pkg/rke2/registries.go
- pkg/rke2/registries_types.go
Signed-off-by: Alberto Morgante Medina <alberto.morgante@suse.com>
(cherry picked from commit c4ba2273d388d68c1881777fc34ad44db8508105)
Fixes #
**Checklist**:
> [release-0.4] Fix issue with registries required fields

- metadata.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
After releasing minor version v0.5.0 we need to update `metadata.yaml` and E2E tests.
Fixes #
**Checklist**:
> :seedling: chore: update metadata.yaml and E2E after release v0.5.0

- .github/workflows/e2e.yml
Based on https://github.com/rancher/cluster-api-provider-rke2/pull/383#issuecomment-2264877065
Fixes #
**Checklist**:
> Remove actions/cache step in e2e tests GH workflow

- .github/workflows/e2e.yml
Signed-off-by: Furkat Gofurov <furkat.gofurov@suse.com>
(cherry picked from commit 613e76e391010e787d6f59fe31b1afef0c5c2381)
Fixes #
**Checklist**:
> [release-0.5] Remove actions/cache step in e2e tests GH workflow

- .github/workflows/release.yml
Signed-off-by: Furkat Gofurov <furkat.gofurov@suse.com>
(cherry picked from commit 8a035f81d251522d81fbe6b971d6a3c067813829)
Fixes #
**Checklist**:
> [release-0.5] Fix release workflow GH action

- .github/CODEOWNERS
- CODEOWNERS
and make @rancher/highlander team as owner
Fixes #
**Checklist**:
> chore: Move CODEOWNERS file to the root of the repo

- metadata.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
Following the post new minor release task described in https://github.com/rancher/cluster-api-provider-rke2/blob/main/docs/release.md#tasks
Fixes #
**Checklist**:
> Prepare main branch for v0.7 development

- docs/release.md
Let's clarify what we imply in our release cadence since we are releasing minor releases more often then what we have noted. Also updates release GH reference to the GH workflow Actions tab
Fixes #
**Checklist**:
> Clarify release cadence

- pkg/rke2/machine_filters.go
Ignore changes injected by Turtles when doing CP rollout. CAPRKE2 keeps infinitely rolling out new control planes after ETCD restore webhook injects system agent installation, this happens because we extended machine config comparison here [https://github.com/rancher/cluster-api-provider-rke2/commit/da42f22bafc1c3e0982a16a2a2fcc15fcbe93b17#diff-efaab5f8d6ccb3ed1[…]d507828a792c692154aR58](https://github.com/rancher/cluster-api-provider-rke2/commit/da42f22bafc1c3e0982a16a2a2fcc15fcbe93b17#diff-efaab5f8d6ccb3ed16e4a43486a08c64daaa1a290f8b5d507828a792c692154aR58)
We can ignore these fields if machine config was mutated by Turtles webhook
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
> Ignore changes injected by Turtles when doing CP rollout

- pkg/rke2/machine_filters.go
Cherry-pick of https://github.com/rancher/cluster-api-provider-rke2/pull/422
Fixes #
**Checklist**:
> [release-0.6] Ignore changes injected by Turtles when doing CP rollout

- README.md
Link newly published book from README.
Fixes #
**Checklist**:
> docs: edit README to add link to book

- .github/workflows/release.yml
Build and publish CAPRKE2 images to prime registry on every new release
Fixes #
**Checklist**:
> Add prime image builds

- controlplane/internal/controllers/rke2controlplane_controller.go
Signed-off-by: Danil-Grigorev <danil.grigorev@suse.com>
(cherry picked from commit 08354a09c6800c946e595c951553028fb6d87171)
Fixes #
**Checklist**:
> Fix: remove pre-terminate drain hook for legacy CP

- .github/workflows/release.yml
> Add missing token permissions for release

- .github/workflows/release.yml
> Use capi forks repo for secret reading

- bootstrap/api/v1alpha1/conversion.go
- bootstrap/api/v1alpha1/zz_generated.conversion.go
- bootstrap/api/v1beta1/rke2config_types.go
- bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
- bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
- controlplane/api/v1alpha1/conversion.go
- controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
- controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
- pkg/rke2/config.go
Add PSA file to the API, this is needed to configure PSA when CIS profile is set
Fixes https://github.com/rancher/cluster-api-provider-rke2/issues/457
**Checklist**:
> Add PSA file to API

- .github/workflows/release.yml
- Makefile
> Use REGISTRY env var based on the actual image pushing registry expected

- .github/workflows/release.yml
- Dockerfile
- Makefile
Moves docker image build to buildx similar to https://github.com/rancher/turtles/pull/724
Fixes #
Co-authored-by: Carlos Salas <carlos.salas@suse.com>
**Checklist**:
> Move from docker build to buildx

- docs/book/src/00_introduction.md
Fix 00_introduction.md bad Developer Guide link.
kind/documentation
> Fix 00_introduction.md bad Developer Guide link

- docs/book/src/01_user/01_getting-started.md
- metadata.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
Follows the post new minor release tasks described in https://github.com/rancher/cluster-api-provider-rke2/blob/main/docs/release.md#tasks and prepares main branch for upcoming v0.9 release
Fixes #
**Checklist**:
> chore: Prepare main branch for v0.9 development

- hack/ensure-kubectl.sh
Use upstream krew-index for crust-gather, see https://github.com/rancher/turtles/pull/868 for more context
Fixes #
**Checklist**:
> Use upstream krew-index for crust-gather

- controlplane/internal/controllers/rke2controlplane_controller.go
The Control plane version must be set in the status to fulfill the API contract.
Fixes https://github.com/rancher/cluster-api-provider-rke2/issues/478
**Checklist**:
> Set control plane version in status

- docs/book/src/01_user/01_getting-started.md
- metadata.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
> Prepare main branch for v0.9 development

- docs/book/src/03_examples/02_vsphere.md
Add warning about kubevip issue to vSphere
Fixes https://github.com/rancher/cluster-api-provider-rke2/issues/511
**Checklist**:
> Add warning about kubevip to vSphere

- examples/docker/air-gapped/rke2-sample.yaml
- examples/docker/cis-profile/rke2-sample.yaml
- examples/docker/clusterclass/clusterclass-quick-start.yaml
- examples/docker/disable-components/rke2-sample.yaml
- examples/docker/enable-multus/rke2-sample.yaml
- examples/docker/kube-vip/rke2-sample.yaml
- examples/docker/online-default/cluster-template.yaml
- test/e2e/data/infrastructure/cluster-template-docker-updated.yaml
- test/e2e/data/infrastructure/cluster-template-docker.yaml
- test/e2e/data/infrastructure/clusterclass-template-docker.yaml
Use success status code to identify unhealthy components and exclude node from LB list.
Fixes #530 
**Checklist**:
> :bug: Use 200 as an expected response from kube-api in haproxy

- docs/old/RKE2 Cluster API Provider - Data Type definitions.md
Fix broken links on old docs as they're causing CI failures.
Fixes #
**Checklist**:
> docs: fix broken links

- docs/book/src/01_user/01_getting-started.md
- metadata.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
> Prepare main branch for v0.11 development

- examples/vmware/cluster-template.yaml
Fixes https://github.com/rancher/cluster-api-provider-rke2/issues/543
**Checklist**:
> Update CPI/CSI part of the vsphere template

- bootstrap/internal/cloudinit/cloudinit.go
- bootstrap/internal/cloudinit/cloudinit_test.go
Adds `additionalUserData.data` content formatting, according to bootstrap cloud-init template indentation.
This change eliminates the need to specify complex values as JSON, such as:
- `{'ephemeral0': '/dev/vdb'}` for maps
- `['data']` for lists
Fixes #527
**Checklist**:
> :bug: Format additionalUserData maps and lists to ensure correct YAML output

- docs/book/src/01_user/01_getting-started.md
- metadata.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
Prepare `main` for v0.12 development.
Fixes #
**Checklist**:
> chore: prepare main branch for v0.12 development

- docs/book/src/01_user/01_getting-started.md
- docs/book/src/04_developer/01_development.md
Makes changes to the development doc based on my experiences in what worked and what didn't. We need this for it to be more useful to future developers.
Fixes # NA
**Checklist**:
> 📖  Development document update and formatting

- docs/book/src/01_user/01_getting-started.md
- test/e2e/config/e2e_conf.yaml
Follow up to #577 
Fixes #
**Checklist**:
> Bump CAPI in e2e config

- bootstrap/internal/ignition/butane/butane_test.go
- docs/book/src/01_user/01_getting-started.md
- metadata.yaml
- pkg/registration/registration_test.go
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
Prepare `main` for v0.13 development.
Fixes #
**Checklist**:
> chore: Prepare main branch for v0.13 development

- docs/book/src/01_user/01_getting-started.md
> Add space in command arguments

- controlplane/api/v1beta1/rke2controlplane_types.go
- controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
- controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
- examples/templates/docker/air-gapped/image-building/README.md
Add missing `DisabledPluginComponent`, which are present in the [rke2 docs]()https://docs.rke2.io/advanced#disabling-server-charts
Fixes #591 
**Checklist**:
- [] includes documentation
> Add additional DisabledPluginComponent

- bootstrap/internal/controllers/rke2config_controller.go
> use RegistrationAddress for first controlPlane node if it is specified

- docs/book/src/01_user/01_getting-started.md
- metadata.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
Prepare `main` branch for v0.14 release
Fixes #
**Checklist**:
> chore: Prepare main branch for v0.14 development

- docs/book/src/01_user/01_getting-started.md
- docs/book/src/02_topics/01_air-gapped-installation.md
> Fix typos in the docs

- examples/templates/openstack/cluster-template.yaml
kind/feature
kind/documentation
Added example to run a rke2-cluster on openstack
> 🌱 Add openstack cluster template to examples

- bootstrap/internal/ignition/butane/butane.go
- bootstrap/internal/ignition/butane/butane_test.go
Fixes https://github.com/rancher/cluster-api-provider-rke2/issues/630
**Checklist**:
> 🐛 Ignition: Don't add /opt fs on flatcar

- pkg/rke2/workload_cluster_test.go
Minor issue spotted in this run: https://github.com/rancher/cluster-api-provider-rke2/actions/runs/14760699865/job/41472773214?pr=627
Fixes #
**Checklist**:
> Fix flaky test

- Makefile
- bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
- bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
- controlplane/api/v1beta1/rke2controlplane_types.go
- controlplane/api/v1beta1/rke2controlplane_webhook.go
- controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
- controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
Default RKE2 control plane replicas to 1 if not specified
Fixes https://github.com/rancher/cluster-api-provider-rke2/issues/622
**Checklist**:
> Default RKE2 control plane replicas to 1 if not specified

- controlplane/api/v1beta1/rke2controlplane_webhook.go
- controlplane/config/rbac/role.yaml
- controlplane/internal/controllers/rke2controlplane_controller.go
- pkg/rke2/control_plane.go
- test/e2e/data/infrastructure/cluster-template-docker-updated.yaml
- test/e2e/data/infrastructure/cluster-template-docker.yaml
- test/e2e/data/infrastructure/cluster-template-kcp-remediation.yaml
- test/e2e/e2e_upgrade_test.go
- test/e2e/helpers.go
This PR adds `Cluster` ownership to the external (Infra)MachineTemplate linked to a RKE2ControlPlane.
Fixes #500
Fixes #616
**Checklist**:
> Reconcile external external owner reference

- docs/book/src/01_user/01_getting-started.md
- metadata.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
https://github.com/rancher/cluster-api-provider-rke2/blob/main/docs/release.md#prepare-main-branch-for-development-of-the-new-release
Fixes #
**Checklist**:
> 🌱 Prepare main branch for v0.16 development

- controlplane/internal/controllers/rke2controlplane_controller.go
- controlplane/internal/controllers/scale.go
Just a little cleanup to consistently use the workloadCluster from the controlPlane scope (instead of controller).
This should have no functional changes.
Fixes #
**Checklist**:
> Cleanup workloadCluster usage

- test/helpers/envtest.go
Just a small PR as an attempt to fix a flaky test. 
I repeated this 13 times and it didn't fail once so far.
Fixes #
**Checklist**:
> Improve test stability

- docs/book/src/01_user/01_getting-started.md
- metadata.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
https://github.com/rancher/cluster-api-provider-rke2/releases/tag/v0.16.0 is out so https://github.com/rancher/cluster-api-provider-rke2/blob/main/docs/release.md#prepare-main-branch-for-development-of-the-new-release
Fixes #
**Checklist**:
> 🌱 Prepare main branch for v0.17 development

- docs/book/src/02_topics/02_node-registration-methods.md
Small documentation fix to actualize the default value.
Fixes #
**Checklist**:
> 📖 Update registrationMethod book documentation

- controlplane/internal/controllers/rke2controlplane_controller.go
(cherry picked from commit 2878e143078494d57ad5f3211071f55f6cc6d067)
Fixes #
**Checklist**:
> 🐛 Backfill missing RKE2ControlPlane fields from legacy format 

- docs/book/src/02_topics/04_embedded-registry.md
- pkg/rke2/registries_types.go
0.16 Backport of https://github.com/rancher/cluster-api-provider-rke2/pull/673
Fixes #
**Checklist**:
> [0.16] Fix private registry token authentication

- docs/book/src/01_user/01_getting-started.md
- metadata.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
> 🌱 Prepare main branch for v0.18 development

- .golangci.yml
- bootstrap/main.go
- controlplane/main.go
> Increase amount of concurrent reconciliations

- docs/book/src/01_user/01_getting-started.md
- metadata.yaml
- test/e2e/config/e2e_conf.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_upgrade_test.go
Prepare main branch for `v0.19.0` develpoment.
Fixes #
**Checklist**:
> chore: prepare main branch for v0.19 development

- bootstrap/api/v1beta1/rke2config_webhook.go
- bootstrap/api/v1beta1/rke2configtemplate_webhook.go
- controlplane/api/v1beta1/rke2controlplane_webhook.go
- controlplane/api/v1beta1/rke2controlplanetemplate_webhook.go
Should restore the previous controller-runtime behavior that is now opt-in with the DefaulterRemoveUnknownOrOmitableFields option.
Fixes #
**Checklist**:
> Use DefaulterRemoveUnknownOrOmitableFields

- bootstrap/api/v1beta1/rke2config_webhook.go
- bootstrap/api/v1beta1/rke2configtemplate_webhook.go
- controlplane/api/v1beta1/rke2controlplane_webhook.go
- controlplane/api/v1beta1/rke2controlplanetemplate_webhook.go
Backport of https://github.com/rancher/cluster-api-provider-rke2/pull/740
Fixes #
**Checklist**:
> [0.20] Use DefaulterRemoveUnknownOrOmitableFields
